# Site settings
title: Robert Wilson
email: robert.wilson1717@gmail.com
url: https://example.github.io
description: "Robert Wilson's Portfolio site"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/rob4002
  - title: facebook
    url:
  - title: bitbucket
    url: http://bitbucket.org/rob4001
  - title: github
    url: http://github.com/rob4001

# Postal address (add as many lines as necessary)
address:
  - line: My House
  - line: Somewhere in Scotland

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
